apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: kuklych-ambulance-ufe-content
spec:
  microFrontend: kuklych-ambulance-ufe
  element: kuklych-ambulance-wl-list
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?kuklych-ambulance-wl(/.*)?$"